- name: Create user
  hosts: centos
  become: yes

  tasks:

    - name: Create groups
      group:
        name: "{{item}}"
        state: present
      loop:
        - dev
        - test

    - name: Create user
      user:
        name: "{{item.username}}"
        shell: /bin/bash
        groups: dev,test
        append: yes
        home: "/home/{{item.home_dir}}"
      with_items:
        - {username: my_user1, home_dir: my_user1}
        - {username: my_user2, home_dir: my_user2}
