- name: loops
  hosts: centos
  become: yes

  tasks:

    - name: Create dir
      file:
        path: "/home/{{ item  }}"
        state: directory
      loop:
        - dir1
        - dir2
        - dir3