---
- name: Install sowtware and check os family
  hosts: all
  become: yes

  vars:
    source_file: /home/vlad/ansible/playbooks/files/index.html
    destin_file: /var/www/html

  tasks:
    - name: Check distrib version
      debug:
        var: ansible_os_family

    - name: Remove Nginx
      yum:
        name: nginx
        state: absent
    - name:
      firewalld:
        service: http
        permanent: yes
        state: enabled
      notify: Reload Firewall
      when: ansible_os_family == "RedHat"

    - name: Install Apache server rpm distribs
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"
      
    - name: Install Apache server dpk distribs
      apt:
        name: apache2
        state: latest
      when: ansible_os_family == "Debian"

    - name: Copy default page to /var/www/html
      copy:
        src: "{{ source_file }}"
        dest: "{{ destin_file }}"
        mode: "0644"
        owner: root
        group: root
      notify: Restart Apache

    - name: Start Web server for RedHat
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Start Web server for Debian
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache RedHat
    service:
      name: httpd
      state: restarted

  - name: Restart Apache Debian
    service:
      name: apache2
      state: restarted

  - name: Restart Firewalld
    service:
      name: firewalld
      state: reloaded
